[scaffolding-chef]
plan_path = "scaffolding-chef"
build_targets = [
  "x86_64-linux",
  "x86_64-linux-kernel2"
  # "x86_64-windows" --- TODO: Expeditor does not currently support Windows, but will in the coming weeks. Uncomment me soon!
]
paths = [
  "scaffolding-chef"
]
