#######################################
# Optional settings
#######################################

# You don't usually need to change these.
# This project provides highly tuned defaults for you.
# If you don't have a strong reason for overriding these
# Then it's a good idea to remove them.

interval = 1800
# The number of seconds to wait between Chef Infra Client runs
# Default value: 1800

splay = 1800
# A random number of seconds between 0 and $splay to add AFTER the interval. Use this setting to avoid the thundering herd problem. Optimal to always set this equal to the interval, or else you may end up DDOSing your own internal resources.
# Default value: 1800

splay_first_run = 0
# A random number of seconds between 0 and $splay_first_run BEFORE the first Chef Infra Client runs, only on the first run. Used to avoid the thundering herd problem on new deployments. Optimal to always set to a function of your node count. Add 1 second for each node in your fleet. For example, if you have 1800 nodes, then you should set this value to 1800.
# Default value: 0

log_level = "warn"
# The level of logging to be stored in a log file for the Chef Infra Client.
# Possible levels: :auto (default), :debug, :info, :warn, :error, or :fatal.
# Default value: :warn (when a terminal is available) or :info (when a terminal is not available).

[automate]
enable = false
server_url = "https://<automate_url>/data-collector/v0/"
token = '<automate_token>'
user = '<automate_user>'
# The connection information for your Chef Automate server
# Setting enable = false will turn off this feature
# The server_url is the url to your Chef Automate Server
# The token is a token with the data_collector rights to the Chef Automate API
# The user is the user that you log in to Chef Automate with, using inspec compliance login
# Default value: false

#######################################
# End of optional settings
#######################################

# You must accept the Chef License to use this software: https://www.chef.io/end-user-license-agreement/
# Change [chef_license] from acceptance = "undefined" to acceptance = "accept-no-persist" if you agree to the license.

[chef_license]
acceptance = "undefined"
